### ISSUE TITLE
Support lenient parser in bindings

### ISSUE THREAD

**Issue by GodTamIt** [quickwit-oss/tantivy-py#109]
Now that https://github.com/quickwit-oss/tantivy/pull/2129 has landed, it'd be nice to start thinking about lenient parsing support in the bindings. Obviously, a new version of the crate has to be released but starting to think about this.

I've started working on this, but there are a few points I'd like to iron out how we'd expose the `QueryParserError` enum. It'd be nice to have types for the errors, but `QueryParserError` is currently a Rust enum.

An (strawman) idea I had was to have separate classes for each error type. Then, optionally, organize them in a submodule underneath `tantivy`, i.e. `tantivy.query_parser_error` or something. Then, the interface could look something like this from the Python side:

```python
@dataclass
class ParseQueryLenientResult:
    query: Query
    errors: List[Union[query_parser_error.SyntaxError, query_parser_error.UnsupportedQuery, ...]]

def parse_query_lenient(query: str, default_field_names: Optional[List[str]]) -> ParseQueryLenientResult:
    ...
```

cc @adamreichold @cjrh if y'all have thoughts

**Comment by adamreichold** [comment]
> Then, the interface could look something like this from the Python side:

Concerning the `Union` type hint, wouldn't a type hierarchy involving inheritance be pretty idiomatic for Python, e.g. `SyntaxError` and `UnsupportedQuery` both inheriting from some `QueryParserError` base class?

**Comment by GodTamIt** [comment]
> > Then, the interface could look something like this from the Python side:
> 
> Concerning the `Union` type hint, wouldn't a type hierarchy involving inheritance be pretty idiomatic for Python, e.g. `SyntaxError` and `UnsupportedQuery` both inheriting from some `QueryParserError` base class?

I posted #114 as a strawman for how this might look.

I played around with using a base class, but there are some challenges with using them with PyO3. I've commented specifically on the PR and in the code about this.
