### ISSUE TITLE
Support Python stub files (.pyi)

### ISSUE THREAD

**Issue by mocobeta** [quickwit-oss/tantivy-py#167]
Currently `tantivy-py` does not include `.pyi` file, so developers have to investigate the source code to figure out what classes/methods are supported in this package.

[PyO3 documentation](https://pyo3.rs/v0.20.0/python_typing_hints) says:

> Yet, for a better user experience, Python libraries should provide typing hints and documentation for all public entities, so that IDEs can show them during development and type analyzing tools such as mypy can use them to properly verify the code.

> Currently the best solution for the problem is to manually maintain *.pyi files and ship them along with the package.

It would be great to have `tantivy.pyi` and `py.typed` in the Python source dir so that developers get the benefits of powerful IDE suggestions and validate their code by linters such as mypy. 
Does this make sense?

Bonus: We could generate API documentation using [pdoc](https://pdoc.dev/) by providing `.pyi` with type stubs.
https://github.com/PyO3/pyo3/discussions/2330

**Comment by mocobeta** [comment]
I opened a draft PR to add `tantivy.pyi`. #168 

Could you take a look? Thank you!

**Comment by cjrh** [comment]
Done!
