### ISSUE TITLE
Get a list of  indexed documents.

### ISSUE THREAD

**Issue by amrit073** [quickwit-oss/tantivy-py#216]
Hi! Is there a plan to add the feature to list all documents that are indexed?  

It would be great to have to implement incremental indexing of new documents.  
We can check if the document is already present in the index before passing the contents for indexing.

**Comment by adamreichold** [comment]
You should be able to search using the [`AllQuery`](https://docs.rs/tantivy/latest/tantivy/query/struct.AllQuery.html) or more efficiently access [`Searcher::segment_readers`](https://docs.rs/tantivy/latest/tantivy/struct.Searcher.html#method.segment_readers) and use [`SegementReader::alive_bitset`](https://docs.rs/tantivy/latest/tantivy/struct.SegmentReader.html#method.alive_bitset) to just iterate all available document ID.

**Comment by cjrh** [comment]
@amrit073 If that answers your question feel free to close the issue 😄

**Comment by amrit073** [comment]
Thanks! Will try to dive into this, maybe try to expose its python bindings.

**Comment by adamreichold** [comment]
I am sorry for not noticing that this was in the `tantivy-py` instead of `tantivy` repository. But do not that you can already access the all-query by just parsing `*` as the query. But yes, segment readers and alive bitsets and not available from Python.
