### ISSUE TITLE
Some documentation issues

### ISSUE THREAD

**Issue by bluebad** [quickwit-oss/tantivy-py#225]
I've encountered several documentation issues. 

In `tantivy.py`, the comment documentation for the Snippet class is incorrect. 

Additionally, after implementing a piece of code for adding indexes based on the example, I faced a "ValueError: An error occurred in a thread: 'An index writer was killed.. A worker thread encountered an error (io::Error most likely) or panicked.'" after calling `index writer.commit()` tens of thousands of times. However, the issue was resolved after following the example in the tests directory, where `writer.wait_merging_threads()` is called after multiple commits. I am not sure if this is an issue on my end, but if it's not, then the documentation should be updated to clarify this process. Thank you for your work!

**Comment by cjrh** [comment]
The documentation is very rough and we know there is a lot of work to be done. We're all volunteers though so fixes happen as time allows.

> comment documentation for the Snippet class is incorrect.

Could you specify in what way it's incorrect? This will help anyone else who comes along and has a few minutes to spare to submit a quick fix for a low-hanging-fruit issue.

> after calling index writer.commit() tens of thousands of times

You should only be calling commit after adding a batch of documents, not after each individual document.

**Comment by bluebad** [comment]
Thank you for your hard work. I just hope to make a contribution to this great project. My comments are not meant to offend or criticize.
Below is the docstring for the Snippet:
```python
class Snippet(object):
    """
    Tantivy schema.
    
    The schema is very strict. To build the schema the `SchemaBuilder` class is
    provided.
    """
```
It seems to have mistakenly used the documentation for Schema.

**Comment by bluebad** [comment]
> You should only be calling commit after adding a batch of documents, not after each individual document.
I did call `add_document` multiple times before committing, approximately once every 1000 calls, but I encountered the error mentioned above. It was not until I used `wait_merging_threads` that I was able to successfully complete the entire indexing process.
