### ISSUE TITLE
Different versions for nox and maturin build

### ISSUE THREAD

**Issue by alex-au-922** [quickwit-oss/tantivy-py#255]
I have found that the python interpreter versions for maturin and nox are in different versions:

```make
# Makefile

build:
	maturin build --interpreter python3.7 python3.8 python3.9 python3.10 python3.11
```

```python
#noxfile.py

@nox.session(python=["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"])
def test(session):
    session.install("-rrequirements-dev.txt")
    session.install("-e", ".", "--no-build-isolation")
    session.run("pytest", *session.posargs)
```

Will this lead to unexpected behavior?

**Comment by cjrh** [comment]
I don't think that makefile is used anywhere. The CI doesn't, for example. I think we should just delete it.

**Comment by alex-au-922** [comment]
I think the makefile is still useful for testing. It helps me build the latest tantivy (local) binary for my testing in one command, I think we should not discard it.

**Comment by cjrh** [comment]
For this I just run `maturin develop` which builds the extension and installs it into a local venv. Is there anything the makefile gives beyond this?

Could you describe your workflow in more detail?

**Comment by alex-au-922** [comment]
> For this I just run `maturin develop` which builds the extension and installs it into a local venv. Is there anything the makefile gives beyond this?
> 
> Could you describe your workflow in more detail?

Oops I just found that the `nox` command does its job. The Makefile should be safe to discard
