### ISSUE TITLE
Publish a package for Python 3.10

### ISSUE THREAD

**Issue by cbenz** [quickwit-oss/tantivy-py#42]
Would it be possible to publish a build of the package for Python 3.10?

Currently, the latest release (0.13.2) stops at Python 3.9: https://pypi.org/project/tantivy/#files

**Comment by fmassot** [comment]
Thanks for opening this issue. Currently, the python bindings are not actively maintained but any PR is welcomed :)

**Comment by cjrh** [comment]
There is an active PR to help with automating releases to PyPI: https://github.com/quickwit-oss/tantivy-py/pull/57

**Comment by pdavies011010** [comment]
Bump ^

I've opened this PR which updates to Tantivy 0.19.2, and also includes python 3.10 and 3.11 as part of the make command (using maturin): [https://github.com/quickwit-oss/tantivy-py/pull/67](https://github.com/quickwit-oss/tantivy-py/pull/67)

**Comment by wallies** [comment]
@cbenz there is now packages for version 0.20.1 for python 3.10 and 3.11 on pypi
