### ISSUE TITLE
Index on Filesystem

### ISSUE THREAD

**Issue by Debdut** [quickwit-oss/tantivy-py#43]
The only doc available is the README.md if I'm not wrong. Quotting from there

```py
# Creating our index (in memory, but filesystem is available too)
index = tantivy.Index(schema)
```

But I don't see any docs for storing the index in filesystem. Any help? 🙏

**Comment by Debdut** [comment]
https://github.com/quickwit-oss/tantivy-py/blob/8e97a1ebe7363bf5dd5f4762eafb31611c3940a1/src/index.rs#L170

Seems from this line of code that, the solution be

```py
index = tantivy.Index(schema, path, True)
```

I'll try and update

**Comment by Sidhant29** [comment]
https://github.com/quickwit-oss/tantivy-py/pull/54

Included in above PR for readme.
