### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by Debdut** [quickwit-oss/tantivy-py#44]
I failed to install while pip installing on a venv on

```yaml
os: MacOS 12.3
rustc: 1.59.0 (9d1b2106e 2022-02-23)
python: 3.9.10
pip: 21.3.1
```

```sh
$ pip install tantivy
Collecting tantivy
  Downloading tantivy-0.13.2.tar.gz (25 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: ///app/py/venv/bin/python3.9 ///app/py/venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /var/folders/kp/wqrkz9nj2b72v_j3nn_l1zvr0000gn/T/tmpil48bddf
       cwd: /private/var/folders/kp/wqrkz9nj2b72v_j3nn_l1zvr0000gn/T/pip-install-5kyggg9_/tantivy_6f911278379c4eebbc4dd392080549dd
  Complete output (6 lines):
  💥 maturin failed
    Caused by: Failed to parse Cargo.toml at Cargo.toml
    Caused by: invalid type: sequence, expected a map for key `package.metadata.maturin.project-url`
  Error running maturin: Command '['maturin', 'pep517', 'write-dist-info', '--metadata-directory', '/private/var/folders/kp/wqrkz9nj2b72v_j3nn_l1zvr0000gn/T/pip-modern-metadata-kep_vd8f', '--interpreter', '///app/py/venv/bin/python3.9']' returned non-zero exit status 1.
  Checking for Rust toolchain....
  Running `maturin pep517 write-dist-info --metadata-directory /private/var/folders/kp/wqrkz9nj2b72v_j3nn_l1zvr0000gn/T/pip-modern-metadata-kep_vd8f --interpreter ///app/py/venv/bin/python3.9`
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/db/9d/84e1888f90680da4e0279dc1df4113287e60d2dd58901bc29fcbe623eed2/tantivy-0.13.2.tar.gz#sha256=5cd63f5664e2df431a43a4c439d6af7d3fd7c8a760dd7303486333d94f6a20c8 (from https://pypi.org/simple/tantivy/) (requires-python:>=3.7). Command errored out with exit status 1: ///app/py/venv/bin/python3.9 ///app/py/venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /var/folders/kp/wqrkz9nj2b72v_j3nn_l1zvr0000gn/T/tmpil48bddf Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement tantivy (from versions: 0.11.0rc7, 0.11.0rc8, 0.12.0rc1, 0.12.0rc2, 0.13.1rc1, 0.13.2)
ERROR: No matching distribution found for tantivy
WARNING: You are using pip version 21.3.1; however, version 22.0.4 is available.
You should consider upgrading via the '///app/py/venv/bin/python3.9 -m pip install --upgrade pip' command.
```

**Comment by Danielmorenorios** [comment]
Be sure that you're using Python 3.9. I had the same issue with the versions above that

**Comment by cjrh** [comment]
We definitely need to make a new release sometime.  Until then, you could try this:

1. Checkout this repo `$ git clone git@github.com:quickwit-oss/tantivy-py.git` (or the https one if you prefer)
1.1 Change into that dir! `$ cd tantiy-py`
2. Make a new python venv, e..g for Python 3.11: `$ python3.11 -m venv venv311`
3. Activate the venv: `$ source venv311/bin/activate`
4. Install a package called Maturin: `(venv311) $ pip install -U pip maturin`
5. Build a wheel for tantivy-py: `(venv311) $ maturin  build`

When this completes, you should have a wheel file in a directory like `./target/wheels/`.  Then, in your "real" venv, the one your own project is in, you should be able to install that wheel file directly.  For example on Linux this would look like:

```bash
$ pip install /home/me/repos/tantivy-py/target/wheels/tantivy-0.20.1-cp311-cp311-manylinux_2_34_x86_64.whl
```

The python version you use to build the wheel file, above, should match the python version that you use to install the wheel file. In my example above it was Python 3.11, but your Python version for your project could be different.

In buiding a wheel file from this tantivy-py repo, it will be using tantivy 0.20.2.

**Comment by wallies** [comment]
@Debdut we pushed a new release to pypi, so you should be able test the install for 0.20.1 now

**Comment by cjrh** [comment]
@Debdut Has any of the above resolved your issue?

**Comment by cjrh** [comment]
We have published wheels for the new version on PyPI for a range of Pythons, so that should have resolved the issue. I will close this issue, but if the same problem persists, I can reopen.
