### ISSUE TITLE
Outdated PyPI package

### ISSUE THREAD

**Issue by EgorDm** [quickwit-oss/tantivy-py#49]
Hi,

The package on PyPI (0.13.2) seems to be outdated (created in 2020).
I was wondering if you are planning on creating a new release that works with tantivy 0.17.

Thanks

**Comment by pdavies011010** [comment]
Bump ^

I've opened this PR which updates to Tantivy 0.19.2, and also includes python 3.10 and 3.11 as part of the make command (using maturin): [https://github.com/quickwit-oss/tantivy-py/pull/67](https://github.com/quickwit-oss/tantivy-py/pull/67)

**Comment by wallies** [comment]
New 0.20.1 package is now on pypi
