### ISSUE TITLE
How to close a index?

### ISSUE THREAD

**Issue by QGB** [quickwit-oss/tantivy-py#58]
i want to delete it's files.

**Comment by cjrh** [comment]
Apologies for the long delay to answer this question.

- If you want to delete all the documents in an index, you can use `writer.delete_all_documents()`, which will leave the index in place as a directory on disk, but will remove all of the previously added documents to that index.
- If you want the index directory gone entirely, just delete the directory, using [`shutil.rmtree`](https://docs.python.org/3/library/shutil.html?highlight=shutil#shutil.rmtree) in Python or `rm -rf <dirname>` in Bash.

Hope that helps. Free to reopen this issue if I didn't answer your question well enough :)
