### ISSUE TITLE
Does someone want to maintain tantivy-py?

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/tantivy-py#73]
Me first and Quickwit in general, has been a very bad steward for the tantivy-py project. Does someone with better python skills want to take over maintaining the project?

**Comment by Sidhant29** [comment]
Hello, I'd be interested in nominating myself. 
I have made PR's for tantivy-py in the past and contribute to the Kapiche fork of tantivy-py regularly as well. (https://github.com/Kapiche/tantivy-py)
I work as a Software Engineer using python everyday and have been getting into rust in the past few months in my spare time.

**Comment by pratyushmittal** [comment]
Hey, thanks a lot @fulmicoton for maintaining this wonderful library. Tantivy and it's Python bindings have enabled us to develop lots of interesting tools.

Unfortunately, we don't know enough of Rust or Python packaging to maintain this project. However, we would like to sponsor it if needed.

Thanks again to you and your whole team at Quickwit.

**Comment by fulmicoton** [comment]
@Sidhant29 Thank you for chiming in. Let's leave the ticket open for a week or so to see if other candidate show up :)

**Comment by fulmicoton** [comment]
@pratyushmittal thank you for your message!

**Comment by cjrh** [comment]
@fulmicoton I am also interested to help maintain tantivy-py. I work directly with @Sidhant29. I have extensive experience maintaining open source packages in Python, and lately increasingly in Rust.

**Comment by wallies** [comment]
@fulmicoton I am also interested to help maintain tantivy-py. I work directly with @Sidhant29 and @cjrh. I work more on the ops side of maintaining open source packages, so building the packages, docker images etc.

**Comment by fulmicoton** [comment]
Alright two weaks have passed...

@Sidhant29  @wallies @cjrh are you all working in the same company or the same opensoure project?
This is definitely the best solution then?

How do we see logistics to pass you the keys?
We want to move the repository I think.

**Comment by wallies** [comment]
@fulmicoton we all work for the same company Kapiche. 

Yeh i think the best bet is to move the repository, as our fork has somethings we could potentially push upstream like our fast field stat searcher. 
I think @poljar has the access to tantivy in pyi. If they want to add me to that project that is that piece. 
We could move the repository here https://github.com/tantivy-oss

**Comment by poljar** [comment]
Oh I never shared access to the PyPi project? Seems to be the case, please let me know who I should add to the project.

**Comment by wallies** [comment]
@poljar can you add my username in pypi is cparry

**Comment by poljar** [comment]
If @fulmicoton agrees to this, sure. @fulmicoton can you confirm?

**Comment by fulmicoton** [comment]
ok with me.

**Comment by poljar** [comment]
Did so.

**Comment by wallies** [comment]
Cheers @poljar. @fulmicoton Did you want to move this repo across to https://github.com/tantivy-oss or should i just fork it and go from there?

**Comment by fulmicoton** [comment]
I'm not sure I am fond of moving it to a repository called tantivy-oss. For the moment we are keeping tantivy in quickwit-oss.

**Comment by fulmicoton** [comment]
I sent you all three an invite to the tantivy-py-admin group. With great power bla bla bla. Be very careful
You were also granted write permission to the tantivy crate. Do not abuse it or I will have to remove that permission.

**Comment by wallies** [comment]
cheers @fulmicoton. I dont seem to have access to add secrets, so i can add the pypi secret token. Is this possible for me to have, otherwise @poljar can do it. Secret will be PYPI_API_TOKEN and TEST_PYPI_API_TOKEN for the test one

**Comment by poljar** [comment]
I don't have access to do this, sorry.

**Comment by wallies** [comment]
@poljar im going to use https://docs.pypi.org/trusted-publishers/adding-a-publisher/ so dont need access to the secrets anymore. Can you add me to the test pypy as well please https://test.pypi.org/project/tantivy/

**Comment by poljar** [comment]
> @poljar im going to use https://docs.pypi.org/trusted-publishers/adding-a-publisher/ so dont need access to the secrets anymore. Can you add me to the test pypy as well please https://test.pypi.org/project/tantivy/

Added there as well.
