### ISSUE TITLE
Bump to PyO3 0.19

### ISSUE THREAD

**Issue by adamreichold** [quickwit-oss/tantivy-py#95]
While Tantivy was bumped to 0.20 recently, PyO3 is still at 0.18 whereas 0.19 is current. I think it would be good to have both major dependencies at the current stable versions before making the next release. The migration guide at https://pyo3.rs/v0.19.1/migration.html?highlight=migration#from-018-to-019 contains some hints on what to look out for when making the change.

**Comment by cjrh** [comment]
#98 Submitted. Fun fact 0.19.1 differs from 0.19.0 by a really bad memory reported by yours truly. Did we have fun in prod with that one!

**Comment by adamreichold** [comment]
I suspect that you mean https://github.com/PyO3/pyo3/issues/3285 ? Note that this was present since 0.18.0 and hence this package was already affected.
