### ISSUE TITLE
Support pickling of certain types

### ISSUE THREAD

**Issue by GodTamIt** [quickwit-oss/tantivy-py#96]
I've found the need for this feature at times for things like `Document`.

Maybe using something like `bincode` and doing:

```python
pub fn __setstate__(&mut self, state: &PyBytes) -> PyResult<()> {
    *self = bincode::deserialize(state.as_bytes()).map_err(...);
    Ok(())
}

pub fn __getstate__<'py>(&self, py: Python<'py>) -> PyResult<&'py PyBytes> {
    Ok(PyBytes::new(py, bincode::serialize(&self).map_err(...))
}
```

Thoughts?

**Comment by adamreichold** [comment]
If this is to go through Serde, then [`pythonize`](https://github.com/davidhewitt/pythonize) (and then pickle as usual) might also be an option.
